name: Lint Code Base

on:
  push:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: PyLint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: sunnysid3up/python-linter@master
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
