name: Lint Code Base

on:
  push:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: PyLint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: ricardochaves/python-lint@v1.4.0
