name: Python Linting
on:
  push:
  pull_request:
jobs:
  lint-python-code:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt install python3-pip -y
          apt-get -y install python3-pip 
          pip3 install flake8
          pip3 install pylint
          if [ -f requirements.txt ]; then pip3 install --target=/usr/bin -r requirements.txt; fi 
      - name: Lint with flake8
        run: |
          /usr/local/bin/flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          /usr/local/bin/flake8 src --count --max-complexity=10 --max-line-length=88 --statistics
      - name: Lint with Pylint
        run: |
          /usr/local/bin/pylint src
          #asd
